#!/usr/bin/env python3
"""Objective coverage checker and EXAM-OBJECTIVE-MAP.md generator.

Reads the canonical MD-102 objective list from objectives.json, scans the repo
for docs, labs and practice questions, and then either:

  * prints a coverage report and exits 1 if any objective lacks a doc or a lab
    (default), or
  * regenerates EXAM-OBJECTIVE-MAP.md (--write-map), or
  * verifies the committed map is up to date (--check-map).

Conventions (see CONTRIBUTING.md):
  docs:      <folder>/docs/<objective-id>-<slug>.md
  labs:      <folder>/labs/LAB-*.md whose first table row lists objective IDs
  questions: 06-Practice-Questions/*.md with lines "**Objective:** x.y.z"
             under a "### Q<id>" heading
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OBJECTIVES = Path(__file__).with_name("objectives.json")
MAP_FILE = ROOT / "EXAM-OBJECTIVE-MAP.md"
ID_RE = re.compile(r"\b(\d\.\d\.\d{1,2})\b")


def load_objectives():
    data = json.loads(OBJECTIVES.read_text(encoding="utf-8"))
    rows = []
    for dom in data["domains"]:
        for skill in dom["skills"]:
            for i, text in enumerate(skill["objectives"], start=1):
                rows.append({
                    "id": f"{skill['id']}.{i}",
                    "text": text,
                    "domain": dom,
                    "skill": skill,
                })
    return data, rows


def find_docs(rows):
    docs = {}
    for r in rows:
        folder = ROOT / r["domain"]["folder"] / "docs"
        matches = sorted(folder.glob(f"{r['id']}-*.md")) if folder.exists() else []
        docs[r["id"]] = matches
    return docs


def find_labs():
    labs: dict[str, list[Path]] = {}
    for lab in sorted(ROOT.glob("0[1-5]-*/labs/LAB-*.md")):
        text = lab.read_text(encoding="utf-8")
        # First markdown table data row after the header separator
        m = re.search(r"^\|[-| :]+\|\s*\n(\|.*\|)", text, flags=re.M)
        if not m:
            continue
        cells = [c.strip() for c in m.group(1).strip("|").split("|")]
        if len(cells) < 2:
            continue
        for oid in ID_RE.findall(cells[1]):
            labs.setdefault(oid, []).append(lab)
    return labs


def find_questions():
    questions: dict[str, list[tuple[Path, str]]] = {}
    for qf in sorted((ROOT / "06-Practice-Questions").glob("*.md")):
        current = None
        for line in qf.read_text(encoding="utf-8").splitlines():
            h = re.match(r"^###\s+(Q[\w.-]+)", line)
            if h:
                current = h.group(1)
                continue
            o = re.match(r"^\*\*Objectives?:\*\*\s*(.+)$", line.strip())
            if o and current:
                for oid in ID_RE.findall(o.group(1)):
                    questions.setdefault(oid, []).append((qf, current))
    return questions


def rel(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


def anchor(q: str) -> str:
    return q.lower().replace(".", "")


def build_map(data, rows, docs, labs, questions) -> str:
    out = [
        "# Exam objective map",
        "",
        f"Traceability matrix for **MD-102 - {data['outline']}** "
        f"([official study guide]({data['source']}), verified {data['verified']}).",
        "Every objective maps to a doc, at least one hands-on lab, and original practice questions.",
        "",
        "> This file is generated by `python3 .github/scripts/check_coverage.py --write-map`. Do not edit by hand.",
        "",
    ]
    total = len(rows)
    with_doc = sum(1 for r in rows if docs[r["id"]])
    with_lab = sum(1 for r in rows if labs.get(r["id"]))
    with_q = sum(1 for r in rows if questions.get(r["id"]))
    out += [
        "| Coverage | Count |",
        "|---|---|",
        f"| Objectives | {total} |",
        f"| With a doc | {with_doc} |",
        f"| With a lab | {with_lab} |",
        f"| With practice questions | {with_q} |",
        "",
    ]
    last_dom = last_skill = None
    for r in rows:
        dom, skill = r["domain"], r["skill"]
        if dom["id"] != last_dom:
            out += [f"## Domain {dom['id']} - {dom['name']} ({dom['weight']})", ""]
            last_dom = dom["id"]
            last_skill = None
        if skill["id"] != last_skill:
            out += [
                f"### {skill['id']} {skill['name']}",
                "",
                "| ID | Objective (verbatim) | Doc | Lab(s) | Questions |",
                "|---|---|---|---|---|",
            ]
            last_skill = skill["id"]
        d = docs[r["id"]]
        doc_cell = f"[doc]({rel(d[0])})" if d else "**MISSING**"
        lab_list = labs.get(r["id"], [])
        lab_cell = ", ".join(
            f"[{p.name.split('-')[0]}-{p.name.split('-')[1]}]({rel(p)})" for p in lab_list
        ) or "**MISSING**"
        q_list = questions.get(r["id"], [])
        q_cell = ", ".join(f"[{q}]({rel(f)}#{anchor(q)})" for f, q in q_list) or "-"
        out.append(f"| {r['id']} | {r['text']} | {doc_cell} | {lab_cell} | {q_cell} |")
        nxt = rows.index(r) + 1
        if nxt == len(rows) or rows[nxt]["skill"]["id"] != skill["id"]:
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-map", action="store_true")
    ap.add_argument("--check-map", action="store_true")
    ap.add_argument("--domains", help="comma-separated domain numbers to enforce (default: all)")
    args = ap.parse_args()

    data, rows = load_objectives()
    docs, labs, questions = find_docs(rows), find_labs(), find_questions()
    content = build_map(data, rows, docs, labs, questions)

    if args.write_map:
        MAP_FILE.write_text(content, encoding="utf-8")
        print(f"Wrote {rel(MAP_FILE)}")
    if args.check_map:
        if not MAP_FILE.exists() or MAP_FILE.read_text(encoding="utf-8") != content:
            print("EXAM-OBJECTIVE-MAP.md is out of date. Run with --write-map and commit.")
            return 1

    enforce = None
    if args.domains is not None:
        enforce = {d.strip() for d in args.domains.split(",") if d.strip()}
    gaps = []
    for r in rows:
        if enforce is not None and r["domain"]["id"] not in enforce:
            continue
        missing = []
        if not docs[r["id"]]:
            missing.append("doc")
        if not labs.get(r["id"]):
            missing.append("lab")
        if missing:
            gaps.append((r["id"], r["text"], missing))

    print(f"Objectives checked: {sum(1 for r in rows if enforce is None or r['domain']['id'] in enforce)}")
    if gaps:
        print(f"Objectives missing coverage: {len(gaps)}")
        for oid, text, missing in gaps:
            print(f"  {oid} [{', '.join(missing)}] {text}")
        return 1
    print("All objectives have at least one doc and one lab.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
